name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main

permissions:
  contents: write
jobs:
  build-docs:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    name: Generate Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0
      - name: Bump version
        uses: rymndhng/release-on-push-action@master
        id: bump-version
        with:
          bump_version_scheme: minor
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Firmware
        uses: esphome/build-action@v7.0.0
        id: esphome-build
        with:
          yaml-file: firmware/plant-waterer.yaml
          complete-manifest: true
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.bump-version.outputs.tag_name }}
          files: ${{ steps.esphome-build.outputs.name }}/*
