name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main

permissions:
  contents: write
jobs:
  build-docs:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-firmware:
    name: Generate esphome firmware
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0
      - name: Build Firmware
        uses: esphome/build-action@v7.0.0
        id: esphome-build
        with:
          yaml-file: firmware/plant-waterer.yaml
          complete-manifest: true
      - name: Upload artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: firmware
          path: ${{ steps.esphome-build.outputs.name }}
